### ISSUE TITLE
AC Compressor Relay Output

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellenNA6_issues#1]
H64 currently has the AC Compressor Relay output(ground) connected to an IN_AUX(GPIOB_0).  We need that changed to an output for ground.

**Comment by Qwerty-OFF** [comment]
Do we need to connect 1J to low-side output?

**Comment by BeerMoneyMotorsports** [comment]
1j needs to provide a ground the relay when AC os active. So im guessing a low side out will work.

**Comment by BeerMoneyMotorsports** [comment]
@Qwerty-OFF did you need anymore info?  i used GPIOH_15 on current board with success.

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/121943083-e1dbe480-cd59-11eb-8357-0d4746d574cf.png)

**Comment by BeerMoneyMotorsports** [comment]
@Qwerty-OFF please confirm that pin is actually OUT_LOW6_PULLUP and NOT 8.  PIN S12 should be OUT_LOW6_PULLUP which i have confirmed works.

**Comment by Qwerty-OFF** [comment]
As a result of the refactoring, the names of the modules pins have changed, but the designation has not changed. We can use any OUT_LOWx to control the AC relay.

**Comment by mck1117** [comment]
@Qwerty-OFF did the mapping of MCU pin to function change?

**Comment by rusefillc** [comment]
@Qwerty-OFF ^^^ ?

**Comment by Qwerty-OFF** [comment]
Done. I will make the changelist after we send the board to production.
