### ISSUE TITLE
Documentation for middle plug

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellenNA6_issues#15]
do we have user documentation for Hellen64 Miata NA6 94 extension port?

I assume that we should have some at least on https://rusefi.com/docs/pinouts/hellen/hellen64_miataNA6_94/ maybe in other locations as well not sure

**Comment by BeerMoneyMotorsports** [comment]
Fixed with https://github.com/rusefi/rusefi/pull/3142 and updates to wiki. 
![image](https://user-images.githubusercontent.com/82395131/129286848-a49296e4-19d6-4abd-a591-7b2ee4a3511b.png)
![image](https://user-images.githubusercontent.com/82395131/129286867-7209580a-5e6f-46d6-bcc8-3b16640da891.png)
