### ISSUE TITLE
Parts shortage 10/27/21

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellenNA6_issues#18]
Parts shortages for order on 10/27/2021.  Please help with alternate options.  

1- R101  C66697  4D03WGF4701T5E  8 4 ±1% 1/16W ±200ppm/℃ 4.7kΩ 1206 Resistor Networks & Arrays ROHS
       --- C149871  8 4 ±1% ±200ppm/℃ 4.7kΩ 100mW 0603x4 Resistor Networks & Arrays ROHS    **_Possible option?_**
2- U410 C37970   MIC5205-3.3YM5-TR   16V 350mV @ 150mA - - Fixed 3.3V SOT-23-5 Linear Voltage Regulators (LDO) ROHS

3- Q305 C174042   ZXMS6005SGTA  SOT-223 Power Distribution Switches ROHS

**Comment by rusefillc** [comment]
I've paid for qty 1000 of ZXMS6005SGTA on my account but still "purchasing"

**Comment by BeerMoneyMotorsports** [comment]
@andreika-git @Qwerty-OFF Can you comment on this being viable option?  

1- R101 C66697 4D03WGF4701T5E 8 4 ±1% 1/16W ±200ppm/℃ 4.7kΩ 1206 Resistor Networks & Arrays ROHS
--- C149871 8 4 ±1% ±200ppm/℃ 4.7kΩ 100mW 0603x4 Resistor Networks & Arrays ROHS Possible option?

**Comment by andreika-git** [comment]
> @andreika-git @Qwerty-OFF Can you comment on this being viable option?
> 
> 1- R101 C66697 4D03WGF4701T5E 8 4 ±1% 1/16W ±200ppm/℃ 4.7kΩ 1206 Resistor Networks & Arrays ROHS --- C149871 8 4 ±1% ±200ppm/℃ 4.7kΩ 100mW 0603x4 Resistor Networks & Arrays ROHS Possible option?

It seems to be almost identical (the corner pads are 0.04mm smaller, but it's totally ok). Let's use it.

**Comment by Qwerty-OFF** [comment]
In replacements for merc128, I used these components:
R101 CRA034RF4K70P05Z_C149871
U410 LP2981-33DBVR_C129997

For INJ (Q305 and other) you can try use BSP78_C56914 but it is not tested
