### ISSUE TITLE
VSS 

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellenNA6_issues#19]
VSS is available on pin 1M for 94-95. Currently has a 5v pullup which is unused on 94/95.  This should be deleted and wired to VSS Input.  VSS input has its own dedicated 5v pullup.  As example, NB1.

**Comment by rusefillc** [comment]
Thats a HW change? Do you have relevant of schematics could help for context

**Comment by BeerMoneyMotorsports** [comment]
delete existing resistor and connection to +5v

![E3D91CD1-78B2-4A2A-BC43-DC9CD1EAEAC1](https://user-images.githubusercontent.com/82395131/141359221-74984fae-64b6-408e-97a1-ff4c2290d865.jpeg)

add connection to VSS(example NB1 pin 2D)
VSS is already connected to STM32, just no connection to pin 1m. 

![DEDE44B8-B46D-415C-8744-2078DAC48452](https://user-images.githubusercontent.com/82395131/141359518-c7fc39af-c1cf-4395-9b10-e8206ce1df7b.jpeg)

schematic showing connection from 1M to VSS

![8BD50D03-4450-4C11-BCD7-152059B48C46](https://user-images.githubusercontent.com/82395131/141359668-2595b879-825a-47c3-bf99-16d74769fe33.jpeg)
![A9E57903-5B62-4F96-ACE5-1205515054A1](https://user-images.githubusercontent.com/82395131/141359669-6650ca7e-64ba-47c6-9e4b-f28d9f1b2ba7.jpeg)

**Comment by rusefillc** [comment]
Hold on, it's not a short. It's a pull-up.

Let's voice talk when you have time.

**Comment by BeerMoneyMotorsports** [comment]
i have updated original problem statement to correct my mistake regarding a short.

**Comment by BeerMoneyMotorsports** [comment]
This is fixed with Rev C.  closing.
