### ISSUE TITLE
USB horizontal on the side

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellenNA6_issues#2]
Please find a way to move this usb area to the edge for external access.  Doing this will also eliminate the need for USB pins in the options port which is not a robust solution.  

![image](https://user-images.githubusercontent.com/82395131/121750676-d0d17000-cada-11eb-9c06-94ba6d86de40.png)

**Comment by BeerMoneyMotorsports** [comment]
Note, if board layers become an issue, conversion to 4 layer is acceptable.

**Comment by BeerMoneyMotorsports** [comment]
@Qwerty-OFF to clarify, we want the H72 platform footprint on the H64 at the edge.  

![image](https://user-images.githubusercontent.com/82395131/121944042-33677d80-cd20-11eb-8b11-77b3c8fcf240.png)

**Comment by Qwerty-OFF** [comment]
Do we need the adapter board?
![image](https://user-images.githubusercontent.com/4116383/122110880-ba534d80-ce27-11eb-8735-9322b4ceece5.png)
Could it be better to use miniUSB or right angle USB -B?

**Comment by stefanst** [comment]
I vote right-angle USB-B. It's f-ing sturdy.

**Comment by mck1117** [comment]
@stefanst you mean like on proteus? is that even possible on this ECU, given its mounting in the car?

**Comment by stefanst** [comment]
I mean right-angle next to the main connector, just like the adapter board.

**Comment by mck1117** [comment]
oh, right angle, not vertical, got it :)

**Comment by Qwerty-OFF** [comment]
Should we kept UA-20PMFP-LC7002 soldering pads?

**Comment by mck1117** [comment]
I think we should have anyway - in addition to whatever USB is on the board.

**Comment by rusefillc** [comment]
NB2 board used small USB board to lift the USB because of rear cover stamped case shape. I do not see similar drama on NA6

I believe we can simply JLC horizontal mini or USB-B
![20210615_171736](https://user-images.githubusercontent.com/48498823/122125205-2a4cde00-cdfe-11eb-970e-b562c31318cc.jpg)

**Comment by BeerMoneyMotorsports** [comment]
please keep the adapter board for now to provide a centered location.  I have 30+ adapters to use.

![image0](https://user-images.githubusercontent.com/82395131/122126567-f2df3100-cdff-11eb-80a0-95962da813aa.jpeg)
![image1](https://user-images.githubusercontent.com/82395131/122126583-f83c7b80-cdff-11eb-97a8-1c8520ed07db.jpeg)

**Comment by BeerMoneyMotorsports** [comment]
after discussion, we can mount direct to board without adapter board.

**Comment by mck1117** [comment]
USB-B (big square one) preferred over mini

**Comment by Qwerty-OFF** [comment]
Please check location of the connector
![image](https://user-images.githubusercontent.com/4116383/122654786-6a8dc280-d156-11eb-99a2-a3c64aada8d0.png)

**Comment by BeerMoneyMotorsports** [comment]
Will the connector be placed during production?  We do not want to use an adapter board. Location is perfect.

**Comment by Qwerty-OFF** [comment]
The connector is JLC part, it will be installed during production

**Comment by BeerMoneyMotorsports** [comment]
@Qwerty-OFF approved.
