### ISSUE TITLE
H64b damaged by NA6 vehicle

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellenNA6_issues#22]
Hellen H64b seems to have bricked while user was installing.  Further investigation required.  I am sending a replacement and getting this unit back for root cause analysis.

https://rusefi.com/forum/viewtopic.php?f=19&t=2212&p=43224#p43224

**Comment by BeerMoneyMotorsports** [comment]
Note- There is no circuit protection on any of the +5v outputs.

At minimum, board will need to be updated with polyfuse on each output.  Possibly C2830230??

Pin 
1N- 1.6 tps
2B- Options Port
3k- 1.8 tps

**Comment by rusefillc** [comment]
This is https://github.com/andreika-git/hellen-one/issues/119

**Comment by BeerMoneyMotorsports** [comment]
rev C added circuit protection
