### ISSUE TITLE
74HC2G17GW,125 shortage

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellenNA6_issues#24]
Latest order of NA6 boards now has a shortage of U490 and 491.  I need support with an alternative part for this order.  I do not see anyone with inventory.

Would it be reasonable to ask jlc to include the needed parts with the order but not installed now that they show inventory?

"For the part (C94189) for U490,U491, I am sorry to tell you that the real stock is insufficient"

<img width="556" alt="image" src="https://user-images.githubusercontent.com/82395131/149555077-92c44f1d-b83b-43da-bb4e-b97bc7fae36d.png">

**Comment by andreika-git** [comment]
Mouser: 771-74HC2G17GWQ100H
"Q100" means "Automotive Electronics Council (AEC) standard Q100 (Grade 1)", so it's even better.
