### ISSUE TITLE
Flex Fuel dropout

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellenNA6_issues#27]
I had some issues with flex % today. I was on a 45 minute drive and it went from 75 to 0 and started running lean. It did this 5 times and every time a complete power cycle fixed it. After stopping for an hour or so, i went back home. It did it once in the first 5 minutes and never again. 

I now have logs of the occurrence.  
https://rusefi.com/online/view.php?log=779

![image](https://user-images.githubusercontent.com/82395131/166341177-e5496154-9ca7-4798-b8d1-088b97d7a61b.png)
![image](https://user-images.githubusercontent.com/82395131/166341194-7ae0f291-89d6-4851-8bcb-a7ddf69b8e2d.png)

Measured the input with the scope.  

![image](https://user-images.githubusercontent.com/82395131/166341412-d43cbee8-5ca2-4a05-9642-ffac68f79a4e.png)

<img width="297" alt="image" src="https://user-images.githubusercontent.com/82395131/166341267-29f87720-c26d-4518-9cd6-c6e62c4db519.png">

There was no change in the signal when the fault occurred.  Signal does show intermittent noise at times during operation. Sensor maintains vbatt.

**Comment by BeerMoneyMotorsports** [comment]
Flex input uses in_sens1 in the hellen input module which ultimately goes to GPIOF-3 on the STM32F4

**Comment by BeerMoneyMotorsports** [comment]
@andreika-git @mck1117

**Comment by mck1117** [comment]
tested with multiple ECUs, or just one?

**Comment by BeerMoneyMotorsports** [comment]
@mck1117 just the one.  I can attempt to try another

**Comment by mck1117** [comment]
you can also try older firmware since we've touched some of this stuff recently

**Comment by BeerMoneyMotorsports** [comment]
I have been running on newer firmware(05/04/22) and driven it a good bit with zero problems.  So firmware seems to be responsible.

**Comment by mck1117** [comment]
ccccccccccccclosed
