### ISSUE TITLE
Additional MAP SSOP-8

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellenNA6_issues#28]
As we discussed @andreika-git Add the smaller SSOP-8 footprint inside the larger MPX4250 footprint for alternate map sensor install.  This will allow usage of some MPXH6400 supplied from JLC.

**Comment by andreika-git** [comment]
Done.
![image](https://user-images.githubusercontent.com/15104768/175553432-bff97a95-7b38-4121-a56c-9e0060c384b9.png)
