### ISSUE TITLE
Wideband input inop

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellenNA6_issues#29]
**Support Log**

Hellen 64 rev B.  
External wideband
Input channel- PA0/ADC_0
Board power- 12v bench supply

TS displays 0 volts with nothing connected for Raw EGO.  
No visible board issues.  
Switching to different input (PA1) shows normal operation of ~5v with nothing connected.  

Tune- https://rusefi.com/online/view.php?msq=1048
Log- https://rusefi.com/online/view.php?log=855
Link for schematic- https://github.com/rusefi/rusefi/wiki/Hardware/Hellen/hellen64_miataNA6_94-b-schematic.pdf

**Comment by rusefillc** [comment]
all units or just one unit?
all sensors or just one random sensor? do you have a reference good unit and reference good sensor?

local or remote?

**Comment by BeerMoneyMotorsports** [comment]
single unit
no sensor connected currently.  was tested previously in the lemon with its sensor. 
Local in hand.

Reference good unit shows ~5v with no sensor connected as expected.

**Comment by BeerMoneyMotorsports** [comment]
I followed the schematics.  found what might have been a poor solder joint on R117.   I applied some solder to it.  I also found what appeared to be a blob of dried flux on the PA0 pin of the STM32.  Removed it as well and now it works as expected.  Confirmed functionality in the lemon.

**Comment by rusefillc** [comment]
Jlc fab defect?

**Comment by BeerMoneyMotorsports** [comment]
yes, jlc fab defect.  do we have a way to feed this back to them?
