### ISSUE TITLE
76 pin header added to BOM and CPL

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellenNA6_issues#33]
76 pin header has been ordered into JLC for soldering in production.  JLC has not provided part # yet.

<img width="897" alt="image" src="https://user-images.githubusercontent.com/82395131/193626323-250c5ea0-5fd6-485e-80c4-94c9aa2ecf21.png">

https://www.verical.com/pd/te-connectivity-headers---pcb-receptacles-5-174915-7-2055967?utm_campaign=octopart_2022&utm_content=inv_listing&utm_currency=USD&utm_keyword=5-174915-7&utm_medium=aggregator&utm_source=octopart

**Comment by BeerMoneyMotorsports** [comment]
Updated, Part number for header is JLCPCB Part #: C5184583

**Comment by andreika-git** [comment]
I suspect that 5-174915-7 is partially incompatible with our 178780-1: leftmost and rightmost holes (big 3.5mm ones) are misaligned!
![image](https://user-images.githubusercontent.com/15104768/194393557-dd8960d4-ba9d-4180-8d0c-c9eac5bdce9f.png)
![image](https://user-images.githubusercontent.com/15104768/194393566-fc8d52fe-eac2-4db7-8d04-1afbfa1f7032.png)

**Comment by BeerMoneyMotorsports** [comment]
this is correct.  when i install them, i clip off the holes on the end.  This is due to parts availability.  The center two holes provide plenty of support.

**Comment by BeerMoneyMotorsports** [comment]
@andreika-git also Q305-312, injector drivers, have a new part number listed below.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/82395131/195419565-e9f43fbc-1992-4bc1-84a0-197ad8c5d663.png">
