### ISSUE TITLE
Rev D LED pinout

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellenNA6_issues#35]
During review between C and D, i missed that the LED pinout is different on the STM32F4.  See screenshots below highlighting the difference.  This results in a critical error.  

Rev C 176 pin
<img width="85" alt="image" src="https://user-images.githubusercontent.com/82395131/200893945-7c16c1e3-2f81-4ff3-8f8b-55588178222c.png">

Rev D 144 pin
<img width="70" alt="image" src="https://user-images.githubusercontent.com/82395131/200894042-0d47f53d-843a-4883-8a2b-5762f7cb6c51.png">

**Comment by rusefillc** [comment]
My forum signature has http://rusefi.com/s/questions in it

http://rusefi.com/s/questions links to https://opensource.com/life/16/10/how-ask-technical-questions

https://opensource.com/life/16/10/how-ask-technical-questions says "If you're getting an error message or debugging information, make sure you include it verbatim."

**Comment by BeerMoneyMotorsports** [comment]
![image](https://user-images.githubusercontent.com/82395131/200903868-02575484-a14c-40be-accf-dab469bb3835.png)

**Comment by rusefillc** [comment]
just pushed a hack which removes the validation from NA6 board

**Comment by BeerMoneyMotorsports** [comment]
I see where i can change the LED pins for 2, 3 and 4 in Tuner studio.  I do not see it for LED 1.  Also, It will revert the pins i change back after power cycle.

**Comment by rusefillc** [comment]
One issue per per one ticket please. I was assuming the focus here was critical error.

**Comment by BeerMoneyMotorsports** [comment]
I confirmed that the error is fixed but that was a symptom of the actual problem.  I assumed you applied the Hack so i could continue validation while we figured out how to fix the LED pin assignment.

**Comment by BeerMoneyMotorsports** [comment]
How can we fix the LED pin selection?  I dont see the ability to change LED1 at all and the other 3 wont save.

**Comment by BeerMoneyMotorsports** [comment]
adding email screenshot here for consistency.  

![image](https://user-images.githubusercontent.com/82395131/201535470-f1c95387-d8d1-41e1-beb5-dbd9f8936666.png)

**Comment by BeerMoneyMotorsports** [comment]
Looks like I need two things to fix this.  There are probably smarter ways but here is what I thought. 
1- add selectable pin for LED-1 (red critical)
2- Not have the LED selections locked in firmware.  I'm assuming that this is what resets them after I manually change the selections for LEDs 2, 3 and 4.  

Other options?  alternate board identifier for the revD with 144 chip?
