### ISSUE TITLE
Options Port Assignments

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellenNA6_issues#5]
@Qwerty-OFF this is to replace https://github.com/rusefi/hellen64_miataNA6_94/issues/50 with concise direction. Please do the following for the H64 options port.  these are in no specific order, please populate whatever pin is best suited for it. Please forgive my lack of knowledge of what the particular I/O should be used on the board.  

** Delete USB in connector **
1- 
2- Replace second H- with H+ tied to 1B with fuse
3- Knock Input
4- Boost Control Output high current low side (possibly needs a diode like IAC)
5- VVT Output high current low side  (possibly needs diode like IAC)
6- GND
7- +5v
8- Aux input
9- VR input(vehicle speed?)
10- Flex( digital input should work?)
11 through 16 wbo

**Comment by stefanst** [comment]
Remarks:

4- Boost Control should have a clamping diode
5- VVT output should have a clamping diode
8- What is AUX input? Analog? Like oil temp, oil pressure?
9- Vehicle speed on a Miata, to the best of my knowledge, is a square wave signal generated by the speedometer on the instrument cluster pin 2F. Not sure if it's 12V or 5V, but I think it's 5V. So a digital input should work, but this needs verification
10- I think flex needs analog input. The signal gives you a percentage of alcohol in the fuel.

**Comment by BeerMoneyMotorsports** [comment]
8- like fuel pressure input or oil pressure
9- unsure on those specifics.  
10- Flex on MS is a digital input but i really do  not know.  @mck1117 had previously noted that it should work on an analog.  maybe use one of the dual inputs that have analog and digital capabilities?

**Comment by stefanst** [comment]
10- It looks like the standard Flex sensor is a digital frequency-based sensor, so any digital or analog input should work, as long as it's interrupt-capable (I guess, but I'm no expert). Or maybe the maximum 150Hz is slow enough that we don't even need an interrupt-capable pin and can just check it at least every 3ms or so.

**Comment by rusefillc** [comment]
Let's try one more time with an online spreadsheet

we are getting towards a yet another 31 comment issue if we are unable to articulate the ask from first go. we have to separate DISCUSSION from DECISION. at the moment this ticket is a set of BAD decisions in my opinion with VR being the worst one but Flex also in bad shape
