### ISSUE TITLE
H64 Options port

### ISSUE THREAD

**Issue by BeerMoneyMotorsports** [rusefi/hellenNA6_issues#6]
@Qwerty-OFF  lets try this again.  Sorry for being confusing.  Please see below for the final info.  Pin position in the connector doesnt matter.  

** Delete USB in connector **  
1-  analog input temperature
2- NC
3- Knock Input  
4- Boost Control Output high current low side (needs a diode like IAC)  
5- VVT Output high current low side (needs diode like IAC)  
6- GND  
7- +5v  
8- analog input  pressure
9- NC
10- digital input(fast)
11- Replace second H- with H+ tied to 1B with fuse   
12 through 16- wbo

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/122115949-aad70300-ce2d-11eb-8920-d188af6f20e9.png)
I think it would be better to place GND instead of NC. What current is required for BOOST and VVT? If more than 1 A, we will need to move at least one of the INJ outputs to OUT_LOWx.
![image](https://user-images.githubusercontent.com/4116383/122116439-49636400-ce2e-11eb-85dc-cc1d26ac147f.png)

**Comment by mck1117** [comment]
move tach/fan to OUT_LOWx outputs, put VVT/boost on INJ outputs (but keep diodes).

**Comment by mck1117** [comment]
> move at least one of the INJ outputs to OUT_LOWx

DO NOT DO THIS

the active clamping on the injector drivers is REQUIRED for injectors, and the OUT_LOWx channels don't have it.  They also won't tolerate the current of an injector.

**Comment by Qwerty-OFF** [comment]
Don't panic! I meant OUT_INJ5-OUT_INJ8 excluding OUT_IDLE :)

**Comment by mck1117** [comment]
oh, ok.  I think it's probably worth putting the guaranteed low current stuff (fan, tach) on OUT_LOWx, and move vvt/boost to the higher current ones

**Comment by rusefillc** [comment]
Regarding fast digital input: PAL stm32 drama plays a role here. we already use GPIOA_6 GPIOB_1 for shat positions. Also GPIOF_11 is already VSS

so whatever pin we use for digital flex cannot be anything 1, 6 or 11

**Comment by Qwerty-OFF** [comment]
Please check options port connections, pull-ups and pull-downs
[hellen64_miataNA6_94-b-schematic.pdf](https://github.com/rusefi/hellenNA6_issues/files/6658916/hellen64_miataNA6_94-b-schematic.pdf)
We have an unused Dinput module for digital inputs. Will we keep it for debugging purposes, or will we remove it?

**Comment by mck1117** [comment]
@Qwerty-OFF did any mappings from STM32 pin to external pin change? OK if the hardware between changed.

**Comment by Qwerty-OFF** [comment]
Yes, there are small changes relative to rev. a like tach, AC relay and maybe something else. If needed i can make changelist after ordering rev. b.

**Comment by mck1117** [comment]
@BeerMoneyMotorsports will that be a problem with the few boards out in the wild, now with different mapping? Or are we willing to replace those boards at cost with rev b?

**Comment by BeerMoneyMotorsports** [comment]
there are a total of 5 H64 boards.  If firmware update is required on them, which it will be, it is a problem.  I would need to hear from @rusefillc to have his thought on replacing them at cost later on if we kill them.  Is it possible to have different firmware for reva and b using two different pin mapping?

**Comment by mck1117** [comment]
> Is it possible to have different firmware for reva and b using two different pin mapping?

this is not worth it for 5 boards

**Comment by BeerMoneyMotorsports** [comment]
@Qwerty-OFF any way to get that change list so i can see if we indeed have a problem?

**Comment by rusefillc** [comment]
@Qwerty-OFF I believe @BeerMoneyMotorsports is asking for all functions which have changed stm32 pins

@BeerMoneyMotorsports what connection functions do you think could have changed stm32 pins?

**Comment by BeerMoneyMotorsports** [comment]
@mck1117 please see the updated schematic.  I think it looks good from a options port pinout but not if those will do exactly what we want.   https://github.com/rusefi/hellenNA6_issues/files/6658916/hellen64_miataNA6_94-b-schematic.pdf

![image0](https://user-images.githubusercontent.com/82395131/122444673-cbf33d00-cf6e-11eb-92a6-6af6b4171487.png)

**Comment by mck1117** [comment]
@Qwerty-OFF IN_TEMP, IN_PRESSURE, and IN_DIGITAL need pull up/downs. 

- IN_TEMP should get the same pullup as the clt/iat inputs
- IN_PRESSURE should get a high value pulldown (680k or whatever)
- IN_DIGITAL should get a 2-4k pullup to 5v.

**Comment by BeerMoneyMotorsports** [comment]
@mck1117 "in digital" is meant for Flex.  Should that remain or should it be changed?

**Comment by mck1117** [comment]
IN_DIGITAL is a fine name, most digital sensors need a pullup anyway.

**Comment by BeerMoneyMotorsports** [comment]
@Qwerty-OFF this sufficient to finalize?

**Comment by Qwerty-OFF** [comment]
Yes, I have installed these pullups and pulldowns and proceed to the PCB. 
![image](https://user-images.githubusercontent.com/4116383/122651922-7ff9f100-d144-11eb-8ee0-125b2b698796.png)

**Comment by BeerMoneyMotorsports** [comment]
Im good with implementation and closing.
